import os
import re
import json
import urllib.parse

def clean_title(filename):
    name = os.path.splitext(filename)[0]
    # Remove resolution tags like @1280w_1l_2o_100sh or @2o or @0o
    name = re.sub(r'@[0-9a-zA-Z_]+', '', name)
    # Remove quality flags
    name = re.sub(r'_quality,[a-zA-Z0-9_]+', '', name)
    
    # If the name is a long hex hash like 01085b5be8e87ca80121ab5d6ac58e or 02706639c457ea3620da960ce45a8e0b_...
    # Keep it readable or format nicely
    if re.match(r'^[0-9a-fA-F_]{20,}$', name):
        name = f"字型标本 {name[:8].upper()}"
    elif name.startswith("字体chuangyi-"):
        num = name.replace("字体chuangyi-", "")
        name = f"创意字型 #{num.zfill(3)}"
    elif "微信图片_" in name:
        date_part = name.replace("微信图片_", "")
        name = f"图样采集 {date_part}"
    
    # Clean up punctuation and spacing
    name = name.strip(" _-")
    if not name:
        name = "字型标本"
    return name

def categorize(filename, filesize):
    ext = os.path.splitext(filename)[1].lower()
    lower = filename.lower()
    
    if ext == '.gif':
        return '动效字体', ['动态演绎', '动态字效']
    
    if 'chuangyi' in lower or '创意' in filename:
        return '创意字形', ['字形重构', '概念实验']
    
    if any(k in filename for k in ['标志', '标准字', 'logo', 'Logo', 'Logotype', '商标']):
        return '标志标准字', ['品牌标识', '商业应用']
        
    if any(k in filename for k in ['部首', '笔画', '黄金分割', '骨骼', '构架']):
        return '笔画构架', ['结构解析', '黄金比例']
        
    if any(k in filename for k in ['书法', '道', '魂', '草', '楷', '行', '水墨', '手写', '無山居人']):
        return '墨韵书法', ['水墨意境', '手写气韵']
        
    if any(k in filename for k in ['海报', 'Poster', '封面', 'COVER', '怪胎', '林柏宏']):
        return '视觉海报', ['版面编排', '展映视效']
        
    if any(k in filename for k in ['日', '日本', '株式会社', '塾', 'ハイスピード', '海と日本', '寺子屋']):
        return '日系字型', ['假名汉字', '东瀛风尚']
        
    if any(k in filename for k in ['大赛', '获奖', '白金创意']):
        return '获奖大作', ['竞赛金奖', '名家典藏']
        
    if 'behance' in lower or 'zcool' in lower or '@' in filename:
        return '现代字型', ['前沿排版', '设计平台']
        
    if filesize > 1200000:
        return '高清巨幅', ['精微细节', '大幅版样']
        
    return '现代字型', ['现代视觉', '灵感版样']

def format_size(size_bytes):
    if size_bytes < 1024:
        return f"{size_bytes} B"
    elif size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.1f} KB"
    else:
        return f"{size_bytes / (1024 * 1024):.1f} MB"

def main():
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    images_dir = os.path.join(root_dir, "1000+优秀字体作品参考")
    
    if not os.path.exists(images_dir):
        print(f"Error: Directory not found: {images_dir}")
        return
        
    valid_exts = {'.jpg', '.jpeg', '.png', '.webp', '.gif'}
    filenames = sorted(os.listdir(images_dir))
    
    catalog = []
    item_id = 1
    
    for fname in filenames:
        ext = os.path.splitext(fname)[1].lower()
        if ext not in valid_exts:
            continue
            
        full_path = os.path.join(images_dir, fname)
        size = os.path.getsize(full_path)
        category, tags = categorize(fname, size)
        title = clean_title(fname)
        
        # Web safe relative path
        rel_path = f"1000+优秀字体作品参考/{urllib.parse.quote(fname)}"
        
        catalog.append({
            "id": item_id,
            "title": title,
            "originalName": fname,
            "category": category,
            "tags": tags,
            "src": rel_path,
            "rawSrc": f"1000+优秀字体作品参考/{fname}",
            "size": format_size(size),
            "sizeBytes": size,
            "ext": ext.lstrip('.').upper()
        })
        item_id += 1
        
    print(f"Catalog generated with {len(catalog)} font specimens.")
    
    # Write to js/catalog-data.js
    js_dir = os.path.join(root_dir, "js")
    os.makedirs(js_dir, exist_ok=True)
    out_file = os.path.join(js_dir, "catalog-data.js")
    
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("// Autogenerated font catalog index\n")
        f.write("window.FONT_CATALOG = ")
        json.dump(catalog, f, ensure_ascii=False, indent=2)
        f.write(";\n")
        
    print(f"Written to {out_file}")

if __name__ == "__main__":
    main()
